name: 'Beta-Export-Server-Deploy'
on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy on beta export server
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy beta export server over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BETA_EXPORT_SERVER_HOST }}
          username: ${{ secrets.BETA_EXPORT_SERVER_USER }}
          key: ${{ secrets.BETA_EXPORT_SERVER_KEY }}
          script_stop: true
          script: ${{ github.workspace }}/beta-export-deploy.sh
