name: 'Beta-Export-Server-Deploy'
on:
  push:
    branches:
      - LF-2758-export-server-CICD

jobs:
  deploy:
    name: Deploy on beta export server
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy beta export server over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.BETA_EXPORT_SERVER_HOST }}
          user: ${{ secrets.BETA_EXPORT_SERVER_USER }}
          key: ${{ secrets.BETA_EXPORT_SERVER_KEY }}
          command: ${{ secrets.BETA_EXPORT_SERVER_SCRIPT }}
