name: Run cypress happy path test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - e2e_test_mika

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      JWT_SECRET: This_will_(really)_work
      JWT_INVITE_SECRET: Any_arbitrary_string_will_do
      JWT_RESET_SECRET: Production_is_secured_with_a_long_random_string
      JWT_FARM_SECRET: Here_we_can_use_friendly_explanations
      JWT_SCHEDULER_SECRET: Another_token_was_needed_for_the_scheduler
      DEV_DATABASE_HOST: localhost
      DEV_DATABASE: pg-litefarm
      DEV_DATABASE_USER: postgres
      DEV_DATABASE_PASSWORD: postgres
      GOOGLE_API_KEY: ${{secrets.VITE_GOOGLE_MAPS_API_KEY}}
      VITE_GOOGLE_MAPS_API_KEY: ${{secrets.VITE_GOOGLE_MAPS_API_KEY}}
      VITE_WEATHER_API_KEY: ${{secrets.VITE_WEATHER_API_KEY}}
      NODE_ENV: development

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      - uses: ikalnytskyi/action-setup-postgres@v3
        with:
          username: ${{env.DEV_DATABASE_USER}}
          password: ${{env.DEV_DATABASE_PASSWORD}}
          database: ${{env.DEV_DATABASE}}
          port: 5432

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run API in background
        working-directory: packages/api
        run: |
          npm ci && cd ../shared && npm ci
          cd ../api && npm run migrate:dev:db
          npm run start &
        env:
          PORT: 5000

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Run Webapp
        working-directory: packages/webapp
        run: |
          pnpm install --config.auto-install-peers=true --no-frozen-lockfile --force
          pnpm dev &
        env:
          VITE_WEATHER_API_KEY: ${{secrets.VITE_WEATHER_API_KEY}}
          VITE_ENV: development
          VITE_GOOGLE_OAUTH_CLIENT_ID: ${{secrets.VITE_GOOGLE_OAUTH_CLIENT_ID}}
          VITE_DO_BUCKET_NAME: litefarm
          NODE_ENV: development
          VITE_API_URL: http://localhost:5000
          CYPRESS_COVERAGE: true

      - name: Run E2E test (English)
        continue-on-error: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_USER: 0
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/end-to-end
          headed: true
          browser: chrome
          record: true
          parallel: false
          group: "UI - Chrome"

      - name: Archive backend logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: packages/api/logs

      - name: set code coverage badge
        working-directory: "."
        run: npx -p check-code-coverage update-badge --from '${GITHUB_WORKSPACE}/packages/end-to-end/coverage/coverage-summary.json'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Set code coverage commit status
        continue-on-error: true
        working-directory: packages/end-to-end
        run: npx set-gh-status
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_SHA: ${{ github.event.after }}
