name: 'Roll out'
on:
  workflow_dispatch:
  push:
    branches:
      - integration
jobs:
  rollout:
    runs-on: ubuntu-20.04
    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'root@avocado.litefarm.org'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            whoami
            pwd
            ls
